### ISSUE TITLE
Test COMSOL license allocation

### ISSUE THREAD

**Issue by robnagler** [radiasoft/vc-multiphysics#2]
@messamer @nickgoldring We need to test how COMSOL allocates licenses. The following experiments should be performed, but maybe you have others:

- [ ] two people login simultaneously as same user and start different, long-running applications
- [ ] two people login sequentially as the same user and start different, long-running applications
- [ ] two people login simultaneously as different users and start long-running applications
- [ ] two people login sequentially as different users and start long-running applications

When I say "long-running", I mean that the run times should overlap. 

It's important we have complete control of the server and that there are no other users logging in. I assume you can arrange this with the other users.

There are other experiments, but this will give us a good start at understanding how COMSOL license allocation works.

**Comment by nickgoldring** [comment]
Sounds good. Thanks, Rob.

I think Paula is in tomorrow so we should be able to knock these out
tomorrow.

Nick

**Comment by messamer** [comment]
Here are the results from the test running in two different browsers on the
same Mac. If they must be run from different computers, let me know.
Paula

1) two people login simultaneously as same user (both remain logged in
during process)  and start different, long-running applications
From Safari, User: radiasoft login, run SRVAC application (no errors)
From Chrome, User: radiasoft login, run Beam Mirror Analyzer application (no
errors)

Result:  Both applications run



2) two people login sequentially as the same user and start different,
long-running applications
From Safari, User: radiasoft, run SRVAC application in browser, user logs
out  (no errors)
From Chrome, User: radiasoft, run Beam Mirror Analyzer application in
browser  (no errors)

Result:  Both applications run



3) two people login simultaneously as different users and start
long-running applications
From Safari, User: radiasoft, run SRVAC application in browser
From Chrome, User: messamer, run Beam Mirror Analyzer application in browser

Result:  messamer can login but gets this error when starting
an application, if press ok, the app looks like its running but it is idle
and is using no CPU time.



Press OK, see this in application tab and this in COMSOL tab




3) two people login simultaneously as different users and start
long-running applications
From Safari, User: radiasoft, run SRVAC application in browser, user logs
out
From Chrome, User: messamer, run Beam Mirror Analyzer application in browser

Result:  messamer can login but gets this error when starting
an application, if press ok, the app looks like its running but it is idle
and is using no CPU time.




Press OK, see this in application tab and this in COMSOL tab

**Comment by robnagler** [comment]
Great stuff, thanks @messamer! One "identity" at a time.

Have we tested running four or five simultaneous simulations? I believe our license is for four simultaneous simulations.

**Comment by messamer** [comment]
You can run 4 simultaneous applications from a single login.  When you
launch the 5th you see this error.

**Comment by bruhwiler** [comment]
@messamer  --   you seem to be referring to images, but I don't see any images in your posts.

PS.  Thanks for the very helpful testing results

**Comment by messamer** [comment]
Sorry-  here is the screenshot showing failure when attempting to launch a
5th simulation.

**Comment by bruhwiler** [comment]
I still don't see an image.
There are a limited range of image formats that GitHub will support

**Comment by messamer** [comment]
.png

**Comment by messamer** [comment]
<img width="1412" alt="comsol_test_4simul" src="https://user-images.githubusercontent.com/29441306/40929515-31f4f12c-67e2-11e8-8a38-421fb57f11af.png">

.png file

**Comment by bruhwiler** [comment]
Now I see it!

**Comment by robnagler** [comment]
Thanks @messamer! I think it's clear now.
